<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>增加数据</title>
</head>
<body>
<form method="post"action="<?php echo $this->baseUrl ?>/index/add/">
   
<table>
	<thead>
	  <tr>
	    <th class="title" colspan="2">增加数据</th>
	  </tr>
	</thead>	
	<tbody>      
	  <tr>
	    <th style="width:25%;">标题</th>
		<td><input type="text" name="title" id="title" value="" size="20"/> <span class="error">*</span></td>
	  </tr>
	  <tr>
	    <th>内容</th>
		<td><textarea name="content" id="content" col="40" row="4"></textarea><span class="error">*</span></td>
	  </tr>
	  
	    <tr>
	    <th colspan="2"><input type="submit" value="增加数据" class="cmd" /></th>
	  </tr>
	  </tbody>
	</table>
</form>


</body>
</html>