<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>增加数据</title>
</head>
<body>
<a href="<?php echo $this->baseUrl ?>/index/add/">增加数据</a>
<table width="500px">
	<thead>
	  <tr>
	    <th class="title" colspan="2">数据列表显示</th>
	  </tr>
	</thead>
	<tbody>
	<tr>
	    <th style="width:25%;">标题</th>
		<th>内容</th>
	</tr>

	<?foreach($this->messages as $message): ?>
	   <tr>
	    <th><?php echo $message['title']; ?></th>
		<td><?php echo $message['content']; ?></td>
	  </tr>
	  <?endforeach; ?>


	  </tbody>
	</table>
</body>
</html>